# Generated by Django 3.2.19 on 2023-09-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('linkcode', models.CharField(blank=True, max_length=100, null=True)),
                ('mostrar', models.BooleanField(default=True, help_text='Visualizar este Video.')),
                ('orden', models.IntegerField(help_text='Orden en el que se publican estos contenidos.')),
            ],
        ),
    ]
