# Generated by Django 3.2.19 on 2023-09-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Multimedia',
        ),
    ]
