# Generated by Django 3.2.19 on 2023-09-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_video_multimedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Ancho máximo de la images en 1980 pixeles', max_length=1980, null=True, upload_to='multimedia/'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='linkcode',
            field=models.CharField(blank=True, help_text='Código de Youtube', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='mostrar',
            field=models.BooleanField(default=True, help_text='Visualizar este multimedia.'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='orden',
            field=models.IntegerField(help_text='Orden en el que se publican estos contenidos multimedia.'),
        ),
    ]
