# Generated by Django 3.2.19 on 2023-10-02 13:59

import apps.home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230912_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='TessW',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='id Nodo Tess-W')),
                ('nombre', models.CharField(max_length=200)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='latitud')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='longitud')),
                ('image', models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 420x420 pixeles', upload_to='tess_location/', validators=[apps.home.validators.validate_image_tess_location])),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'ON'), (1, 'OFF'), (2, 'FAIL')], default=0, null=True)),
            ],
        ),
    ]
