# Generated by Django 3.2.19 on 2023-10-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tessw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tessw',
            options={'verbose_name_plural': 'Tess-W Nodes'},
        ),
        migrations.RenameField(
            model_name='tessw',
            old_name='nombre',
            new_name='name',
        ),
    ]
