# Generated by Django 3.2.19 on 2023-10-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20231002_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TessW',
        ),
    ]
