# Generated by Django 3.2.21 on 2023-12-15 15:23

import apps.home.validators
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_tessw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('titulo', models.CharField(max_length=300)),
                ('resumen', models.CharField(max_length=500)),
                ('cuerpo', ckeditor_uploader.fields.RichTextUploadingField(max_length=15000)),
                ('imagen', models.ImageField(help_text='Tamano maximo de la imagen es de 1Mb y sus dimensiones deben ser de 370x240px', upload_to='noticias/', validators=[apps.home.validators.validate_image_noticia])),
                ('mostrar', models.BooleanField(default=True, help_text='Visualizar Noticia.')),
                ('mostrar_principal', models.BooleanField(default=False, help_text='Visualizar actividad en index del sitio.')),
            ],
            options={
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha'],
            },
        ),
    ]
