# Generated by Django 3.2.21 on 2024-08-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('indice', models.IntegerField()),
                ('imagen_hd', models.ImageField(upload_to='media/fotos_hd/')),
                ('imagen_thumb', models.ImageField(blank=True, null=True, upload_to='media/fotos_thumb/')),
                ('mostrar', models.BooleanField(default=True, help_text='Visualizar Imagen.')),
                ('mostrar_principal', models.BooleanField(default=False, help_text='Visualizar imagen en index del sitio.')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('institucion', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(default=None, max_length=254, unique=True)),
                ('archivo_csv_luminarias', models.FileField(default=None, upload_to='media/luminarias/')),
                ('archivo_imagen_pago', models.FileField(default=None, upload_to='media/pagos/')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
