# Generated by Django 3.2.21 on 2024-08-16 19:35

import apps.home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_galeria_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Ancho máximo de la images en 1980 pixeles', max_length=1980, null=True, upload_to='media/multimedia/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(help_text='Tamano maximo de la imagen es de 1Mb y sus dimensiones deben ser de 370x240px', upload_to='media/noticias/', validators=[apps.home.validators.validate_image_noticia]),
        ),
    ]
