# Generated by Django 3.2.22 on 2023-11-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_lastmonth_lastnight_lastweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastmonth',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastweek',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
