# Generated by Django 3.2.22 on 2023-11-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20231109_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessw',
            name='last_ambient_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tessw',
            name='last_frequency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tessw',
            name='last_magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tessw',
            name='last_sky_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
