# Generated by Django 3.2.25 on 2024-04-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_moon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastnight',
            name='day',
        ),
        migrations.RemoveField(
            model_name='lastnight',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='lastnight',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='lastnight',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='lastnight',
            name='second',
        ),
    ]
