# Generated by Django 3.2.25 on 2024-04-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20240405_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastmonth',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lastmonth',
            name='day',
        ),
        migrations.RemoveField(
            model_name='lastmonth',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='lastweek',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lastweek',
            name='day',
        ),
        migrations.RemoveField(
            model_name='lastweek',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='lastweek',
            name='hour',
        ),
        migrations.AddField(
            model_name='lastmonth',
            name='record_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastweek',
            name='record_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
