# Generated by Django 3.2.25 on 2024-04-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20240405_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessw',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tessw',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tessw',
            name='mean_magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tessw',
            name='start_time_mean_magnitude',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tessw',
            name='stop_time_mean_magnitude',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
