# Generated by Django 3.2.25 on 2024-04-17 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20240417_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tessw',
            old_name='index',
            new_name='bortle_level',
        ),
    ]
