# Generated by Django 3.2.25 on 2024-06-05 21:20

import apps.dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_index_tessw_bortle_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tessw',
            name='image',
            field=models.ImageField(blank=True, help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 420x420 pixeles', null=True, upload_to='tess_location/', validators=[apps.dashboard.validators.validate_image_tess_location]),
        ),
    ]
