# Generated by Django 3.2.25 on 2024-06-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_tessw_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('calculation_datetime', models.DateTimeField()),
                ('calculation_date', models.DateField()),
                ('median_magnitude', models.FloatField(blank=True, null=True)),
                ('median_magnitude_clear', models.FloatField(blank=True, null=True)),
                ('median_magnitude_covered', models.FloatField(blank=True, null=True)),
                ('median_magnitude_cloudy', models.FloatField(blank=True, null=True)),
                ('stddev_magnitude', models.FloatField(blank=True, null=True)),
                ('stddev_magnitude_clear', models.FloatField(blank=True, null=True)),
                ('stddev_magnitude_covered', models.FloatField(blank=True, null=True)),
                ('stddev_magnitude_cloudy', models.FloatField(blank=True, null=True)),
                ('bortle_level', models.IntegerField(blank=True, null=True)),
                ('total_measurements_month', models.IntegerField(blank=True, null=True)),
                ('percentage_measurements_month', models.FloatField(blank=True, null=True)),
                ('tess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tessw')),
            ],
            options={
                'verbose_name_plural': 'Historical Values',
            },
        ),
    ]
