# Generated by Django 3.2.25 on 2024-06-18 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_historicalvalues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tessw',
            old_name='mean_magnitude',
            new_name='media_magnitude',
        ),
        migrations.RenameField(
            model_name='tessw',
            old_name='start_time_mean_magnitude',
            new_name='start_time_media_magnitude',
        ),
        migrations.RenameField(
            model_name='tessw',
            old_name='stop_time_mean_magnitude',
            new_name='stop_time_media_magnitude',
        ),
    ]
