# Generated by Django 3.2.25 on 2024-06-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20240618_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tessw',
            old_name='media_magnitude',
            new_name='median_magnitude',
        ),
        migrations.RenameField(
            model_name='tessw',
            old_name='start_time_media_magnitude',
            new_name='start_time_median_magnitude',
        ),
        migrations.RenameField(
            model_name='tessw',
            old_name='stop_time_media_magnitude',
            new_name='stop_time_median_magnitude',
        ),
    ]
