# Generated by Django 3.2.25 on 2024-06-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20240618_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvalues',
            name='calculation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
