# Generated by Django 3.2.25 on 2024-07-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_historicalvalues_calculation_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvalues',
            name='percentage_measurements_clear',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalvalues',
            name='percentage_measurements_cloudy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalvalues',
            name='percentage_measurements_covered',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalvalues',
            name='total_measurements_clear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalvalues',
            name='total_measurements_cloudy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalvalues',
            name='total_measurements_covered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tessw',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='comuna'),
        ),
    ]
