# Generated by Django 3.2.25 on 2024-07-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20240715_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessw',
            name='commune',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='comuna'),
        ),
        migrations.AlterField(
            model_name='tessw',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='localidad'),
        ),
    ]
