# Generated by Django 3.2.25 on 2024-08-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20240715_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessw',
            name='financiamiento',
            field=models.IntegerField(blank=True, choices=[(0, 'FIC-R  Región de Coquimbo 2022'), (1, 'ESO Comité Mixto-Gobierno de Chile  2021')], null=True),
        ),
    ]
