# Generated by Django 3.2.25 on 2024-10-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_tessw_financiamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessw',
            name='region',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='región'),
        ),
        migrations.AlterField(
            model_name='tessw',
            name='financiamiento',
            field=models.IntegerField(blank=True, choices=[(0, 'FIC-R Región de Coquimbo 2022'), (1, 'ESO Comité Mixto-Gobierno de Chile 2021')], null=True),
        ),
    ]
