# Generated by Django 3.2.25 on 2024-10-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20241014_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('load_date', models.DateField()),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('record_time', models.DateField(blank=True, null=True)),
                ('tess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tessw')),
            ],
            options={
                'verbose_name_plural': 'Historical Values',
            },
        ),
    ]
