# Generated by Django 3.2.21 on 2024-10-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_monthvalues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthValues',
        ),
    ]
