# Generated by Django 3.2.25 on 2024-10-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_delete_monthvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvalues',
            name='data_url',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
