# Generated by Django 3.2.21 on 2024-11-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_historicalvalues_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessw',
            name='institution_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tessw',
            name='solar',
            field=models.BooleanField(default=True),
        ),
    ]
