# Generated by Django 3.2.21 on 2024-11-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20241104_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tessw',
            name='solar',
            field=models.BooleanField(default=False),
        ),
    ]
