# Generated by Django 3.2.25 on 2024-11-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_tessw_solar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessw',
            name='institution_email_verification',
            field=models.BooleanField(default=False),
        ),
    ]
