# Generated by Django 5.2.8 on 2025-11-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_tessw_institution_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tessw',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='id Nodo'),
        ),
    ]
