# Generated by Django 5.2.8 on 2025-11-20 18:20

import apps.dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_tessw_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tess4C',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='id Nodo')),
                ('name', models.CharField(max_length=200)),
                ('commune', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='comuna')),
                ('location', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='localidad')),
                ('region', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='región')),
                ('financiamiento', models.IntegerField(blank=True, choices=[(0, 'FIC-R Región de Coquimbo 2022'), (1, 'ESO Comité Mixto-Gobierno de Chile 2021')], null=True)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='latitud')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='longitud')),
                ('image', models.ImageField(blank=True, help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 420x420 pixeles', null=True, upload_to='tess_location/', validators=[apps.dashboard.validators.validate_image_tess_location])),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('last_frequency', models.FloatField(blank=True, null=True)),
                ('last_magnitude', models.FloatField(blank=True, null=True)),
                ('last_frequency_f2', models.FloatField(blank=True, null=True)),
                ('last_magnitude_f2', models.FloatField(blank=True, null=True)),
                ('last_frequency_f3', models.FloatField(blank=True, null=True)),
                ('last_magnitude_f3', models.FloatField(blank=True, null=True)),
                ('last_frequency_f4', models.FloatField(blank=True, null=True)),
                ('last_magnitude_f4', models.FloatField(blank=True, null=True)),
                ('last_ambient_temperature', models.FloatField(blank=True, null=True)),
                ('last_sky_temperature', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'ON'), (1, 'OFF'), (2, 'FAIL')], default=0, null=True)),
                ('median_magnitude', models.FloatField(blank=True, null=True)),
                ('start_time_median_magnitude', models.DateTimeField(blank=True, null=True)),
                ('stop_time_median_magnitude', models.DateTimeField(blank=True, null=True)),
                ('bortle_level', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('institution_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('institution_email_verification', models.BooleanField(default=False)),
                ('solar', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tess-W Nodes',
            },
        ),
    ]
