# Generated by Django 5.2.8 on 2025-11-20 18:23

import apps.dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_tess4c'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQC',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='id Nodo')),
                ('name', models.CharField(max_length=200)),
                ('commune', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='comuna')),
                ('location', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='localidad')),
                ('region', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='región')),
                ('financiamiento', models.IntegerField(blank=True, choices=[(0, 'FIC-R Región de Coquimbo 2022'), (1, 'ESO Comité Mixto-Gobierno de Chile 2021')], null=True)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='latitud')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='longitud')),
                ('image', models.ImageField(blank=True, help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 420x420 pixeles', null=True, upload_to='tess_location/', validators=[apps.dashboard.validators.validate_image_tess_location])),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('bortle_level', models.IntegerField(blank=True, null=True)),
                ('zenith_magnitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
