# Generated by Django 5.2.8 on 2025-11-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_sqc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqc',
            options={'verbose_name_plural': 'SQCs'},
        ),
        migrations.AlterModelOptions(
            name='tess4c',
            options={'verbose_name_plural': 'Tess4C Nodes'},
        ),
    ]
