# Generated by Django 5.2.8 on 2026-01-02 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_sqc_options_alter_tess4c_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastnight',
            name='tess',
        ),
        migrations.CreateModel(
            name='LastNightTessW',
            fields=[
                ('lastnight_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.lastnight')),
                ('tess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tessw')),
            ],
            bases=('dashboard.lastnight',),
        ),
    ]
