# Generated by Django 5.2.8 on 2026-01-02 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_remove_lastnight_tess_lastnighttessw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastweek',
            name='tess',
        ),
        migrations.CreateModel(
            name='LastWeekTessW',
            fields=[
                ('lastweek_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.lastweek')),
                ('tess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tessw')),
            ],
            bases=('dashboard.lastweek',),
        ),
    ]
