# Generated by Django 5.2.8 on 2026-01-02 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_remove_lastweek_tess_lastweektessw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastmonth',
            name='tess',
        ),
        migrations.CreateModel(
            name='LastMonthTessW',
            fields=[
                ('lastmonth_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.lastmonth')),
                ('tess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tessw')),
            ],
            bases=('dashboard.lastmonth',),
        ),
    ]
