# Generated by Django 5.2.8 on 2026-01-02 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_remove_lastmonth_tess_lastmonthtessw'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastMonthTess4C',
            fields=[
                ('lastmonth_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.lastmonth')),
                ('tess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tess4c')),
            ],
            bases=('dashboard.lastmonth',),
        ),
        migrations.CreateModel(
            name='LastNightTess4C',
            fields=[
                ('lastnight_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.lastnight')),
                ('tess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tess4c')),
            ],
            bases=('dashboard.lastnight',),
        ),
        migrations.CreateModel(
            name='LastWeekTess4C',
            fields=[
                ('lastweek_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.lastweek')),
                ('tess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tess4c')),
            ],
            bases=('dashboard.lastweek',),
        ),
    ]
