# Generated by Django 5.2.8 on 2026-01-02 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_lastmonthtess4c_lastnighttess4c_lastweektess4c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvalues',
            name='tess',
        ),
        migrations.CreateModel(
            name='HistoricalValuesTess4C',
            fields=[
                ('historicalvalues_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.historicalvalues')),
                ('tess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tess4c')),
            ],
            bases=('dashboard.historicalvalues',),
        ),
        migrations.CreateModel(
            name='HistoricalValuesTessW',
            fields=[
                ('historicalvalues_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.historicalvalues')),
                ('tess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tessw')),
            ],
            bases=('dashboard.historicalvalues',),
        ),
    ]
