# Generated by Django 5.2.8 on 2026-03-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_remove_historicalvalues_tess_historicalvaluestess4c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqc',
            name='device_type',
            field=models.CharField(blank=True, choices=[('TessW', 'TessW'), ('Tess4C', 'Tess4C'), ('SQC', 'SQC')], null=True),
        ),
        migrations.AddField(
            model_name='tess4c',
            name='device_type',
            field=models.CharField(blank=True, choices=[('TessW', 'TessW'), ('Tess4C', 'Tess4C'), ('SQC', 'SQC')], null=True),
        ),
        migrations.AddField(
            model_name='tessw',
            name='device_type',
            field=models.CharField(blank=True, choices=[('TessW', 'TessW'), ('Tess4C', 'Tess4C'), ('SQC', 'SQC')], null=True),
        ),
    ]
