# Generated by Django 5.2.8 on 2026-03-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_sqc_device_type_tess4c_device_type_tessw_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqc',
            name='device_type',
            field=models.IntegerField(blank=True, choices=[(1, 'TessW'), (2, 'Tess4C'), (3, 'SQC')], null=True),
        ),
        migrations.AlterField(
            model_name='tess4c',
            name='device_type',
            field=models.IntegerField(blank=True, choices=[(1, 'TessW'), (2, 'Tess4C'), (3, 'SQC')], null=True),
        ),
        migrations.AlterField(
            model_name='tessw',
            name='device_type',
            field=models.IntegerField(blank=True, choices=[(1, 'TessW'), (2, 'Tess4C'), (3, 'SQC')], null=True),
        ),
    ]
